In [ ]:
#!pip install gym
#!pip install pygame

In [1]:
import gym
import numpy as np

In [2]:
env = gym.make('CartPole-v1', render_mode='human')

In [3]:
def epsilon_greedy_policy(state, Q, epsilon=0.1):
    explore = np.random.binomial(1, epsilon)
    if explore:
        action = env.action_space.sample()
        print('explore')
    else:
        action = np.argmax(Q[state])
        print('exploit')
    return action

In [4]:
def optimal_policy(state, Q):
    action = np.argmax(Q[state])
    return action

In [5]:
bins = np.linspace(-0.000001, 100., 2)
bins

array([-1.e-06,  1.e+02])

In [6]:
def get_state(obs):
    d = np.digitize(obs, bins)
    state = tuple(d)
    return state

In [7]:
state = get_state(np.array([-1.4, -2., 0.23, 1.2]))
state

(0, 0, 1, 1)

In [8]:
Q = np.random.random((2,2,2,2,2))
Q

array([[[[[0.31476072, 0.19956056],
          [0.47793227, 0.15548624]],

         [[0.4867365 , 0.61111695],
          [0.2568281 , 0.50649214]]],


        [[[0.7148789 , 0.53508648],
          [0.32645208, 0.25970681]],

         [[0.35499329, 0.6444892 ],
          [0.86946716, 0.88015813]]]],



       [[[[0.59498046, 0.01235932],
          [0.95448547, 0.45129908]],

         [[0.0858123 , 0.87761156],
          [0.96263835, 0.492098  ]]],


        [[[0.51308354, 0.71286953],
          [0.33384059, 0.37896812]],

         [[0.6301944 , 0.72135008],
          [0.77047255, 0.10523372]]]]])

In [9]:
obs, _ = env.reset()
print(obs)
done = False
while not done:
    state = get_state(obs)
    action = epsilon_greedy_policy(state, Q, 0.5)
    obs, reward, done, info, _ = env.step(action)
    print('->', state, action, reward, obs, done, info)
env.close()

[ 0.03107319 -0.02544639  0.00567179  0.03583372]
exploit
-> (1, 0, 1, 1) 0 1.0 [ 0.03056426 -0.22064921  0.00638846  0.33030075] False False
exploit
-> (1, 0, 1, 1) 0 1.0 [ 0.02615128 -0.41586152  0.01299448  0.6249914 ] False False
explore
-> (1, 0, 1, 1) 1 1.0 [ 0.01783405 -0.22092336  0.02549431  0.33642915] False False
explore
-> (1, 0, 1, 1) 0 1.0 [ 0.01341558 -0.41639867  0.03222289  0.63704133] False False
explore
-> (1, 0, 1, 1) 1 1.0 [ 0.00508761 -0.22174054  0.04496372  0.35467762] False False
explore
-> (1, 0, 1, 1) 1 1.0 [ 0.00065279 -0.0272858   0.05205727  0.07650519] False False
explore
-> (1, 0, 1, 1) 1 1.0 [ 1.0707854e-04  1.6705272e-01  5.3587373e-02 -1.9930977e-01] False False
explore
-> (1, 1, 1, 0) 0 1.0 [ 0.00344813 -0.0287931   0.04960118  0.10978442] False False
explore
-> (1, 0, 1, 1) 0 1.0 [ 0.00287227 -0.22458944  0.05179686  0.41769448] False False
explore
-> (1, 0, 1, 1) 1 1.0 [-0.00161952 -0.03023831  0.06015075  0.14178024] False False
exploit
-> (0, 0, 

: 